import type { UserRoleName } from "@/types/database";

export const PERMISSIONS = {
  // Platform-wide (Super Admin)
  PLATFORM_MANAGE: "platform:manage",
  PLATFORM_ANALYTICS: "platform:analytics",
  PLATFORM_SUBSCRIPTIONS: "platform:subscriptions",

  // School administration
  SCHOOL_MANAGE: "school:manage",
  SCHOOL_BRANDING: "school:branding",
  SCHOOL_SETTINGS: "school:settings",

  // People management
  STUDENTS_MANAGE: "students:manage",
  TEACHERS_MANAGE: "teachers:manage",
  PARENTS_MANAGE: "parents:manage",

  // Academic structure
  CLASSES_MANAGE: "classes:manage",
  SUBJECTS_MANAGE: "subjects:manage",
  SESSIONS_MANAGE: "sessions:manage",

  // Learning
  COURSES_MANAGE: "courses:manage",
  LESSONS_MANAGE: "lessons:manage",
  COURSES_VIEW: "courses:view",
  LESSONS_VIEW: "lessons:view",
  MATERIALS_VIEW: "materials:view",

  // Assignments
  ASSIGNMENTS_MANAGE: "assignments:manage",
  ASSIGNMENTS_SUBMIT: "assignments:submit",
  ASSIGNMENTS_GRADE: "assignments:grade",

  // CBT / Examinations
  QUESTION_BANK_MANAGE: "question-bank:manage",
  EXAMINATIONS_MANAGE: "examinations:manage",
  EXAMINATIONS_TAKE: "examinations:take",
  EXAMINATIONS_VIEW: "examinations:view",

  // Results
  RESULTS_VIEW: "results:view",
  RESULTS_MANAGE: "results:manage",

  // Analytics
  ACADEMIC_ANALYTICS: "academic:analytics",
  STUDENT_ANALYTICS: "student:analytics",

  // Engagement
  ANNOUNCEMENTS_MANAGE: "announcements:manage",
  ANNOUNCEMENTS_VIEW: "announcements:view",
  NOTIFICATIONS_VIEW: "notifications:view",

  // Parent portal
  CHILDREN_VIEW: "children:view",

  // School fees (per-child invoicing and payment approval)
  FEES_MANAGE: "fees:manage",
  FEES_APPROVE: "fees:approve",
  FEES_VIEW: "fees:view",
  FEES_PAY: "fees:pay",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<UserRoleName, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  SCHOOL_OWNER: [
    PERMISSIONS.SCHOOL_MANAGE,
    PERMISSIONS.SCHOOL_BRANDING,
    PERMISSIONS.SCHOOL_SETTINGS,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.TEACHERS_MANAGE,
    PERMISSIONS.PARENTS_MANAGE,
    PERMISSIONS.CLASSES_MANAGE,
    PERMISSIONS.SUBJECTS_MANAGE,
    PERMISSIONS.SESSIONS_MANAGE,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.LESSONS_MANAGE,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.LESSONS_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.ASSIGNMENTS_MANAGE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.QUESTION_BANK_MANAGE,
    PERMISSIONS.EXAMINATIONS_MANAGE,
    PERMISSIONS.EXAMINATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_MANAGE,
    PERMISSIONS.ACADEMIC_ANALYTICS,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.FEES_APPROVE,
    PERMISSIONS.FEES_VIEW,
  ],

  SCHOOL_ADMIN: [
    PERMISSIONS.SCHOOL_SETTINGS,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.TEACHERS_MANAGE,
    PERMISSIONS.PARENTS_MANAGE,
    PERMISSIONS.CLASSES_MANAGE,
    PERMISSIONS.SUBJECTS_MANAGE,
    PERMISSIONS.SESSIONS_MANAGE,
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.LESSONS_MANAGE,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.LESSONS_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.ASSIGNMENTS_MANAGE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.QUESTION_BANK_MANAGE,
    PERMISSIONS.EXAMINATIONS_MANAGE,
    PERMISSIONS.EXAMINATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_MANAGE,
    PERMISSIONS.ACADEMIC_ANALYTICS,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.FEES_MANAGE,
    PERMISSIONS.FEES_APPROVE,
    PERMISSIONS.FEES_VIEW,
  ],

  PRINCIPAL: [
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.LESSONS_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.EXAMINATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.ACADEMIC_ANALYTICS,
    PERMISSIONS.ANNOUNCEMENTS_MANAGE,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  TEACHER: [
    PERMISSIONS.COURSES_MANAGE,
    PERMISSIONS.LESSONS_MANAGE,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.LESSONS_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.ASSIGNMENTS_MANAGE,
    PERMISSIONS.ASSIGNMENTS_GRADE,
    PERMISSIONS.QUESTION_BANK_MANAGE,
    PERMISSIONS.EXAMINATIONS_MANAGE,
    PERMISSIONS.EXAMINATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.ACADEMIC_ANALYTICS,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  STUDENT: [
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.LESSONS_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.ASSIGNMENTS_SUBMIT,
    PERMISSIONS.EXAMINATIONS_TAKE,
    PERMISSIONS.EXAMINATIONS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.STUDENT_ANALYTICS,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
  ],

  PARENT: [
    PERMISSIONS.CHILDREN_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANNOUNCEMENTS_VIEW,
    PERMISSIONS.STUDENT_ANALYTICS,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_PAY,
  ],
};

export function getPermissionsForRole(
  role: UserRoleName | null | undefined,
): Permission[] {
  if (!role) return [];
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(
  role: UserRoleName | null | undefined,
  permission: Permission,
): boolean {
  return getPermissionsForRole(role).includes(permission);
}