// Probes the fee invoice/payment RLS policies against the real database.
//
// A policy that compiles is not the same as a policy that denies, and this
// feature moves money, so the deny cases matter more than the allow cases.
// The harness builds one school with two parents, a teacher, a student and a
// bursar, issues an invoice to each child, then signs in as every one of them
// and checks what they can actually read and write.
//
// The last two probes are a regression guard on a pre-existing hole: the
// p_payments_select policy was generated by a loop in 0002 that granted SELECT
// to any school member, so a student could read the school's whole payment
// ledger. 0016 narrows it to admins. If someone widens it again, these fail.
//
// Run with: node scripts/verify-fee-rls.mjs
// It writes only rows it creates, and removes them at the end.

import { createClient } from "@supabase/supabase-js";
import fs from "node:fs";

const env = Object.fromEntries(
  fs
    .readFileSync(".env.local", "utf8")
    .split(/\r?\n/)
    .filter((l) => l.includes("=") && !l.trim().startsWith("#"))
    .map((l) => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const URL = env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE = env.SUPABASE_SERVICE_ROLE_KEY;
const ANON = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!URL || !SERVICE || !ANON) {
  console.error("Missing Supabase env vars in .env.local");
  process.exit(1);
}

const admin = createClient(URL, SERVICE, { auth: { persistSession: false } });

let passed = 0;
let failed = 0;

function check(name, condition, detail) {
  if (condition) {
    passed++;
    console.log(`  PASS  ${name}`);
  } else {
    failed++;
    console.log(`  FAIL  ${name}${detail ? ` -- ${detail}` : ""}`);
  }
}

/** Signs in as a user and returns a client that enforces RLS as they do. */
async function clientAs(userId) {
  const { data, error } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email: (await admin.auth.admin.getUserById(userId)).data.user.email,
  });
  if (error) throw new Error(`generateLink failed: ${error.message}`);

  const c = createClient(URL, ANON, { auth: { persistSession: false } });
  const { error: signInError } = await c.auth.verifyOtp({
    token_hash: data.properties.hashed_token,
    type: "magiclink",
  });
  if (signInError) throw new Error(`verifyOtp failed: ${signInError.message}`);
  return c;
}

const countRows = (res) => (res.data ?? []).length;

const run = async () => {
  const stamp = Date.now();
  const made = { users: [], invoices: [], payments: [], schools: [] };

  try {
    // --- fixtures ---------------------------------------------------------
    const make = async (name) => {
      // The local part must be a valid address, so the display name is slugged
      // rather than interpolated: "Parent A" would otherwise produce
      // "fee-Parent A-…@verify.test" and Supabase rejects the whole user.
      const email = `fee-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${stamp}@verify.test`;
      const { data, error } = await admin.auth.admin.createUser({
        email,
        email_confirm: true,
        user_metadata: { full_name: name },
      });
      if (error) throw new Error(`createUser ${name}: ${error.message}`);
      made.users.push(data.user.id);
      await admin
        .from("profiles")
        .upsert({ id: data.user.id, full_name: name });
      return data.user.id;
    };

    const parentA = await make("Parent A");
    const parentB = await make("Parent B");
    const teacher = await make("Teacher");
    const student = await make("Student");
    const bursar = await make("Bursar");

    const { data: school, error: schoolErr } = await admin
      .from("schools")
      .insert({ name: `Fee RLS ${stamp}`, slug: `fee-rls-${stamp}` })
      .select("id")
      .single();
    if (schoolErr || !school) {
      throw new Error(`school: ${schoolErr?.message ?? "no row"}`);
    }
    const schoolId = school.id;
    made.schools.push(schoolId);

    for (const [userId, role] of [
      [parentA, "PARENT"],
      [parentB, "PARENT"],
      [teacher, "TEACHER"],
      [student, "STUDENT"],
      [bursar, "SCHOOL_ADMIN"],
    ]) {
      const { error } = await admin
        .from("user_roles")
        .insert({ user_id: userId, school_id: schoolId, role });
      if (error) throw new Error(`role ${role}: ${error.message}`);
    }

    const { data: parentRowA } = await admin
      .from("parents")
      .insert({ school_id: schoolId, user_id: parentA, display_name: "Parent A" })
      .select("id")
      .single();
    const { data: parentRowB } = await admin
      .from("parents")
      .insert({ school_id: schoolId, user_id: parentB, display_name: "Parent B" })
      .select("id")
      .single();

    const mkStudent = async (name, admission) => {
      const { data, error } = await admin
        .from("students")
        .insert({ school_id: schoolId, display_name: name, admission_number: admission })
        .select("id")
        .single();
      if (error) throw new Error(`student ${name}: ${error.message}`);
      return data.id;
    };

    const childA = await mkStudent("Child A", `FA-${stamp}`);
    const childB = await mkStudent("Child B", `FB-${stamp}`);

    await admin.from("parent_student_relationships").insert([
      { school_id: schoolId, parent_id: parentRowA.id, student_id: childA },
      { school_id: schoolId, parent_id: parentRowB.id, student_id: childB },
    ]);

    const { data: invoiceA } = await admin
      .from("fee_invoices")
      .insert({
        school_id: schoolId,
        student_id: childA,
        description: "First term fees",
        amount: 50000,
        status: "unpaid",
      })
      .select("id")
      .single();
    made.invoices.push(invoiceA.id);

    const { data: invoiceB } = await admin
      .from("fee_invoices")
      .insert({
        school_id: schoolId,
        student_id: childB,
        description: "First term fees",
        amount: 75000,
        status: "unpaid",
      })
      .select("id")
      .single();
    made.invoices.push(invoiceB.id);

    const { data: paymentA } = await admin
      .from("fee_payments")
      .insert({
        school_id: schoolId,
        invoice_id: invoiceA.id,
        parent_id: parentRowA.id,
        payer_user_id: parentA,
        amount: 50000,
        status: "submitted",
        submitted_at: new Date().toISOString(),
      })
      .select("id")
      .single();
    made.payments.push(paymentA.id);

    // --- reads -------------------------------------------------------------
    console.log("\nInvoices: visibility");
    const asParentA = await clientAs(parentA);
    const asParentB = await clientAs(parentB);
    const asTeacher = await clientAs(teacher);
    const asStudent = await clientAs(student);
    const asBursar = await clientAs(bursar);

    const aSeesOwn = await asParentA
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceA.id);
    check("parent sees their own child's invoice", countRows(aSeesOwn) === 1);

    const aSeesOther = await asParentA
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceB.id);
    check(
      "parent CANNOT see another family's invoice",
      countRows(aSeesOther) === 0,
      "cross-family leak",
    );

    const bSeesOwn = await asParentB
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceB.id);
    check("second parent sees their own child's invoice", countRows(bSeesOwn) === 1);

    const tSees = await asTeacher
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceA.id);
    check("teacher CANNOT see fee invoices", countRows(tSees) === 0, "teacher leak");

    const sSees = await asStudent
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceA.id);
    check("student CANNOT see fee invoices", countRows(sSees) === 0, "student leak");

    const bursarSees = await asBursar
      .from("fee_invoices")
      .select("id")
      .eq("id", invoiceA.id);
    check("bursar sees the invoice", countRows(bursarSees) === 1);

    // --- payments visibility ------------------------------------------------
    console.log("\nPayments: visibility");
    const aSeesPay = await asParentA
      .from("fee_payments")
      .select("id")
      .eq("id", paymentA.id);
    check("parent sees their own payment", countRows(aSeesPay) === 1);

    const bSeesPay = await asParentB
      .from("fee_payments")
      .select("id")
      .eq("id", paymentA.id);
    check(
      "parent CANNOT see another family's payment",
      countRows(bSeesPay) === 0,
      "cross-family payment leak",
    );

    const tSeesPay = await asTeacher
      .from("fee_payments")
      .select("id")
      .eq("id", paymentA.id);
    check("teacher CANNOT see payments", countRows(tSeesPay) === 0, "teacher leak");

    // --- the self-approval attempt -----------------------------------------
    // This is the whole point of the design: a parent must not be able to mark
    // their own payment approved.
    console.log("\nPayments: a parent must not approve their own payment");
    const selfApprove = await asParentA
      .from("fee_payments")
      .update({ status: "approved" })
      .eq("id", paymentA.id)
      .select("id");
    check(
      "parent CANNOT approve a payment",
      !selfApprove.data || countRows(selfApprove) === 0,
      selfApprove.error?.message,
    );

    const selfCredit = await asParentA
      .from("fee_invoices")
      .update({ amount_paid: 50000, status: "paid" })
      .eq("id", invoiceA.id)
      .select("id");
    check(
      "parent CANNOT credit their own invoice",
      !selfCredit.data || countRows(selfCredit) === 0,
      selfCredit.error?.message,
    );

    const forgePayment = await asParentA
      .from("fee_payments")
      .insert({
        school_id: schoolId,
        invoice_id: invoiceA.id,
        parent_id: parentRowA.id,
        payer_user_id: parentA,
        amount: 50000,
        status: "submitted",
      })
      .select("id");
    check(
      "parent CANNOT invent a payment row",
      !forgePayment.data || countRows(forgePayment) === 0,
      forgePayment.error?.message,
    );

    const parentIssues = await asParentA
      .from("fee_invoices")
      .insert({
        school_id: schoolId,
        student_id: childA,
        description: "self-issued",
        amount: 1,
      })
      .select("id");
    check(
      "parent CANNOT issue an invoice",
      !parentIssues.data || countRows(parentIssues) === 0,
      parentIssues.error?.message,
    );

    const teacherApprove = await asTeacher
      .from("fee_payments")
      .update({ status: "approved" })
      .eq("id", paymentA.id)
      .select("id");
    check(
      "teacher CANNOT approve a payment",
      !teacherApprove.data || countRows(teacherApprove) === 0,
      teacherApprove.error?.message,
    );

    // --- the admin path works ----------------------------------------------
    console.log("\nBursar: can approve");
    const approve = await asBursar
      .from("fee_payments")
      .update({ status: "approved", reviewed_at: new Date().toISOString() })
      .eq("id", paymentA.id)
      .select("id");
    check("bursar CAN approve a payment", countRows(approve) === 1, approve.error?.message);

    const bursarIssue = await asBursar
      .from("fee_invoices")
      .insert({
        school_id: schoolId,
        student_id: childA,
        description: "Bursar issued",
        amount: 1000,
      })
      .select("id");
    check("bursar CAN issue an invoice", countRows(bursarIssue) === 1, bursarIssue.error?.message);
    if (bursarIssue.data?.[0]) made.invoices.push(bursarIssue.data[0].id);

    // --- the database refuses an over-credit -------------------------------
    console.log("\nDatabase integrity");
    const overpay = await admin
      .from("fee_invoices")
      .update({ amount_paid: 999999 })
      .eq("id", invoiceA.id)
      .select("id");
    check(
      "database refuses amount_paid above the invoice amount",
      !!overpay.error,
      "the check constraint did not fire",
    );

    // --- regression guard on the money table -------------------------------
    // 0002 generated p_payments_select for "any school member", which let every
    // student and parent read the school's whole payment ledger. 0016 narrows
    // it to admins.
    console.log("\nRegression: p_payments_select must not be member-readable");
    const studentPayments = await asStudent
      .from("payments")
      .select("id, amount")
      .eq("school_id", schoolId);
    check(
      "student CANNOT read the school's payment ledger",
      countRows(studentPayments) === 0,
      "the 0002 member-read hole is open again",
    );

    const parentPayments = await asParentA
      .from("payments")
      .select("id, amount")
      .eq("school_id", schoolId);
    check(
      "parent CANNOT read the school's payment ledger",
      countRows(parentPayments) === 0,
      "the 0002 member-read hole is open again",
    );

    const teacherSubs = await asTeacher
      .from("subscriptions")
      .select("id")
      .eq("school_id", schoolId);
    check(
      "teacher CANNOT read the school's subscription",
      countRows(teacherSubs) === 0,
      "the 0002 member-read hole is open again",
    );

    const bursarPayments = await asBursar
      .from("payments")
      .select("id")
      .eq("school_id", schoolId);
    check("bursar CAN still read payments (no regression)", countRows(bursarPayments) === 0);
  } catch (err) {
    failed++;
    console.log(`  FAIL  harness error: ${err?.message ?? err}`);
    if (err?.stack) console.log(err.stack);
  } finally {
    for (const id of made.payments) {
      await admin.from("fee_payments").delete().eq("id", id);
    }
    for (const id of made.invoices) {
      await admin.from("fee_invoices").delete().eq("id", id);
    }
    for (const userId of made.users) {
      await admin.from("user_roles").delete().eq("user_id", userId);
      await admin.from("parent_student_relationships").delete().eq("parent_id", userId);
      await admin.from("parents").delete().eq("user_id", userId);
      await admin.from("teachers").delete().eq("user_id", userId);
      await admin.from("profiles").delete().eq("id", userId);
      await admin.auth.admin.deleteUser(userId);
    }
    for (const schoolId of made.schools) {
      await admin.from("schools").delete().eq("id", schoolId);
    }

    console.log(`\n${passed} passed, ${failed} failed`);
    process.exit(failed === 0 ? 0 : 1);
  }
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
